### ISSUE TITLE
Flag editable

### ISSUE THREAD

**Issue by feinfinger** [tango-controls/waltz#214]
In order to avoid accidental additions to carefully predefined tables, a checkbox that makes tables editable would be helpful. That box should be unchecked (not editable) by default.

**Comment by Ingvord** [comment]
@feinfinger , thanks a lot for the suggestion!

Below is how it looks like:

![st-pt-accommodations2](https://user-images.githubusercontent.com/11678364/62166077-88669a00-b328-11e9-87a1-67c3add70a5b.png)

Settings panel is now visible by default as well. Otherwise there is a confusion - user can't do anything with a table unless he/she clicks on :gear: and set the flag. Should be fine now I guess.

**Comment by Ingvord** [comment]
Should be checked by default; stored in context
